; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/mobizt/Firebase-ESP-Client.git#v4.4.17
	bblanchon/ArduinoJson@^6.21.2
	paulstoffregen/Time
	arduino-libraries/NTPClient
	liquidcrystal_i2c
	bogde/HX711
	wire
	miguelbalboa/MFRC522@^1.4.12
build_flags = 
	-Ilib/Firebase-ESP-Client/src
	-Iinclude
